# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1


executors:
  node-executor:
    docker:
      - image: node:latest
        #auth:
          #username: mydockerhub-user
          #password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    working_directory: /react-app

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  create-react-app-if-none: 
    executor: node-executor
    steps:
      - checkout
      - run:
          name: looking for react project named "code"
          command: |
            if [ ! -d "code" ]; then # if dir not exists...
              npx create-react-app code
              echo "created react app named 'code' "
            else
              echo "app already exists"
            fi
  build-react-app:
    executor: node-executor
    steps:
      -checkout
      - run:
          name: build react code
          command: |
            cd code
            npm install
            npm run build
      - run:
          name: create-image
          command: |
            # code (use build number)
      - run:
          name: push-to-ecr
          command: |
            # code
  
        

workflows:
  react-node-workflow: 
    jobs:
      - create-react-app-if-none
      - build-react-app:
        requires: create-react-app-if-none
